apiVersion: v1
kind: Service 
metadata: 
  app: mywebapp-service 
spec: 
  selector:
    app: mywebapp 
  ports:
    -protocol: TCP 
    port: 5000
    targetPort : 5000
    nodePort : 30080 
  type: NodePort 
  